# Generated by Django 2.1.2 on 2018-10-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0002_book_info_site_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
